-- V3: cria tabela aluno

CREATE TABLE IF NOT EXISTS aluno (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  senha VARCHAR(255) NOT NULL,
  cpf VARCHAR(50) NOT NULL UNIQUE,
  rg VARCHAR(50),
  nome VARCHAR(255) NOT NULL,
  endereco VARCHAR(255),
  saldo_moedas INT DEFAULT 0,
  curso VARCHAR(255),
  role VARCHAR(50) NOT NULL DEFAULT 'ALUNO'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
